{{- if eq (include "penpot.adminConsoleEnabled" .) "true" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "penpot.fullname" . }}-admin-console
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "penpot.labels" . | nindent 4 }}
  {{- with .Values.adminConsole.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.adminConsole.autoscaling.hpa.enabled }}
  replicas: {{ .Values.adminConsole.replicaCount }}
  {{- end }}
  strategy:
    {{- toYaml .Values.adminConsole.updateStrategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "penpot.adminConsoleSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: penpot-admin-console
        {{- include "penpot.adminConsoleSelectorLabels" . | nindent 8 }}
        {{- with .Values.adminConsole.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.adminConsole.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "penpot.serviceAccountName" . }}
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (include "penpot.podSecurityContext" (dict "ctx" . "values" .Values.adminConsole.podSecurityContext)) }}
      securityContext:
        {{- . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-admin-console
          image: "{{ .Values.adminConsole.image.repository }}:{{ .Values.adminConsole.image.tag }}"
          imagePullPolicy: {{ .Values.adminConsole.image.pullPolicy | default .Values.adminConsole.image.imagePullPolicy }}
          {{- with (include "penpot.containerSecurityContext" (dict "ctx" . "values" .Values.adminConsole.containerSecurityContext)) }}
          securityContext:
            {{- . | nindent 12 }}
          {{- end }}
          env:
            - name: PENPOT_PUBLIC_URI
              value: {{ .Values.config.publicUri | quote }}
            - name: PENPOT_INTERNAL_URI
              value: {{ print "http://" (include "penpot.fullname" .) ":" .Values.frontend.service.port }}
            - name: PENPOT_SECRET_KEY
              {{- if not .Values.config.secretKeys.apiSecretKey }}
              value: {{ .Values.config.apiSecretKey | quote }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.existingSecret }}
                  key: {{ .Values.config.secretKeys.apiSecretKey }}
              {{- end }}
            # PosgreSQL connection settings
            - name: PENPOT_DATABASE_URI
              {{- if not .Values.config.postgresql.secretKeys.postgresqlUriKey }}
              value: "postgresql://{{ .Values.config.postgresql.host }}:{{ .Values.config.postgresql.port }}/{{ .Values.config.postgresql.database }}"
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.postgresql.existingSecret }}
                  key: {{ .Values.config.postgresql.secretKeys.postgresqlUriKey }}
              {{- end }}
            - name: PENPOT_DATABASE_USERNAME
              {{- if not .Values.config.postgresql.secretKeys.usernameKey }}
              value: {{ .Values.config.postgresql.username | quote }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.postgresql.existingSecret }}
                  key: {{ .Values.config.postgresql.secretKeys.usernameKey }}
              {{- end }}
            - name: PENPOT_DATABASE_PASSWORD
              {{- if not .Values.config.postgresql.secretKeys.passwordKey }}
              value: {{ .Values.config.postgresql.password | quote }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.postgresql.existingSecret }}
                  key: {{ .Values.config.postgresql.secretKeys.passwordKey }}
              {{- end }}
            # Extra environments
          {{- with .Values.config.extraEnvs }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.adminConsole.extraEnvs }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- with .Values.adminConsole.volumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.adminConsole.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.adminConsole.resources | nindent 12 }}
      {{- with .Values.adminConsole.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.adminConsole.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.adminConsole.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- with .Values.adminConsole.volumes }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
{{- end }}
