{{- if .Values.frontend.autoscaling.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "penpot.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "penpot.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "penpot.fullname" . }}-frontend
  minReplicas: {{ .Values.frontend.autoscaling.hpa.minReplicas }}
  maxReplicas: {{ .Values.frontend.autoscaling.hpa.maxReplicas }}
  metrics:
    {{- toYaml .Values.frontend.autoscaling.hpa.metrics | nindent 4 }}
{{- end }}
