apiVersion: v1
kind: Service
metadata:
  name: {{ include "penpot.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "penpot.labels" . | nindent 4 }}
  {{- if .Values.frontend.service.annotations }}
  annotations:
    {{- .Values.frontend.service.annotations | toYaml | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "penpot.frontendSelectorLabels" . | nindent 4 }}
