{{- if .Values.migration.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-cnpg-db-secret
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  username: {{ .Values.config.postgresql.username | quote }}
  password: {{ .Values.config.postgresql.password | quote }}
{{- end }}
