---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: penpot
  labels:
    app: postgresql
spec:
  type: ClusterIP
  selector:
    app: postgresql
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
      protocol: TCP
